### ISSUE TITLE
[Audit] hardfork unfriendly gas cost

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#400]
https://github.com/thehubbleproject/hubble-contracts/blob/32234da0ce3015b4bece04a264a136a6778191dd/contracts/libs/BLS.sol#L103
Specifying explicitly precompile cost could be unfriendly to future hardforks.

**Comment by ChihChengLiang** [comment]
Instead, we should use `sub(gas(), 2000)` which is a standard way people are doing.
https://github.com/iden3/snarkjs/blob/master/templates/verifier_groth16.sol#L83

**Comment by kilic** [comment]
In signature verification, we interpret _precompile revert_ signal for:

* signature is not a valid point
* any of pubkeys which are G2 points are not valid point or in incorrect subgroup

While first issue would be checked before precompile call, latter is infeasible in EVM.

So we have be sure that caller supplied enough gas to run precompile. If fraud caller is supplied insufficient gas then precompile [reverts](https://github.com/ethereum/go-ethereum/blob/d667ee2d1063faad0b4347db498bda00f34a1ba6/core/vm/contracts.go#L134) and we couldn't check if coordinator used bad pubkey which is valid fraud detection or precompile just reverted because of insufficient gas.

Our approach enforces that fraud detector must supply enough gas for precompile calls or transaction would revert because of out of gas.

For hardfork compatibility:

1. We assume that pairing precompile cost will never increase in future HF. This is the current approach and sounds a bit fishy
2. We can deploy another contract that can be called by anyone and calculates approx pairing precompile cost with predefined valid inputs. And then we can fetch current const of the precompile costs.

**Comment by snjax** [comment]
@kilic, 2nd way seems safer.

**Comment by ChihChengLiang** [comment]
Fixed in #409
